### ISSUE TITLE
Can't set values for null NumberElements

### ISSUE THREAD

**Issue by kvangorkom** [magao-x/purepyindi#2]
Trying to send a value to a `NumberElement` that has a value of None results in a TypeError.

Example:
```
>>> client = indi.INDIClient('localhost', 7626)
>>> client.start()
>>> print(client['wooferModes.target_amps.00'])
None
>>> client['wooferModes.target_amps.00']  = 0.1

Exception in thread INDIClient-sender:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/dev/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/miniconda3/envs/dev/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/envs/dev/lib/python3.7/site-packages/purepyindi-0.1.0-py3.7.egg/purepyindi/client.py", line 52, in _sender
    outdata = mutation_to_xml_message(mutation)
  File "/opt/miniconda3/envs/dev/lib/python3.7/site-packages/purepyindi-0.1.0-py3.7.egg/purepyindi/generator.py", line 50, in mutation_to_xml_message
    xml_doc = construct_property_new(mutation, timestamp)
  File "/opt/miniconda3/envs/dev/lib/python3.7/site-packages/purepyindi-0.1.0-py3.7.egg/purepyindi/generator.py", line 29, in construct_property_new
    sub.text = element['format'] % (element['value'],)
TypeError: must be real number, not NoneType
```

**Comment by joseph-long** [comment]
Should be addressed by 2bd16e9. Going to leave this open to hopefully shame me into writing a test for it...

**Comment by joseph-long** [comment]
You verified this fixed it, right? Looking at the code I'm unable to remember why `element['value']` would be None if you were setting it to something else...

**Comment by kvangorkom** [comment]
Hmm, yeah. I have only foggy memories of this now, but I think we would have run into this all throughout the 2019B run if it hadn't been fixed.

**Comment by joseph-long** [comment]
Yeah, agreed.
